spring:
  profiles:
    active: dev  
  main:
    banner-mode: off
server:  port: 8083

#logging configuration
logging:
  level:
    com.bhoomi: DEBUG
    org.springframework: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR 
  file: logs\application.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
#logging configuration ended
---

#Spring configuration
spring:
  #Datasource configuration
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:port;DatabaseName=MYDB;
    username: userName
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:      
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #Datasource configuration ended 
  profiles: dev
#Spring configuration ended

#Actuator Props
management:  endpoints:    web:      exposure:        include: "*"
  endpoint:
    health:
      show-details: always
#Actuator Props end

---

#Spring configuration
spring:
  #Datasource configuration
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:port;DatabaseName=db;
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:      
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #Datasource configuration ended
  
  profiles: test
#Spring configuration ended

---


#Spring configuration
spring:
  #Datasource configuration
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:port;DatabaseName=db;
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:      
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #Datasource configuration ended
  
  profiles: prod
#Spring configuration ended
